[Admin] Api get categories
AT-PHPIntership/product-tiki pull request #116
Opened 2018-06-07 07:42 UTC by at-khadinh

## Description
Api get categories.
## Reference Requirements

## Reference Isuees

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-06-07 08:44 UTC, at-mailuong commented
LGTM

2018-06-11 03:32 UTC, ghost requested changes
plz check

2018-06-11 03:32 UTC, at-huenguyen commented on app/Http/Controllers/Api/User/CategoryController.php
> +            $this->getCategoryChilds($childCategories, $categoriesAll);
em ko nên dùng kiểu đệ quy vại, trường hợp cực phức tạp mình mới nên sài đệ quy.
em có thể thử như này: 
`Category::where('level', 0)->with('children. children')->get();`

2018-06-11 06:00 UTC, at-mailuong commented
LGTM

2018-06-11 09:31 UTC, ghost approved these changes

2018-06-11 09:31 UTC, merged