Unit test api get comments
AT-PHPIntership/product-tiki pull request #142
Opened 2018-06-13 07:52 UTC by at-khadinh

## Description
Add unit test for api get comments.
## Reference Requirements

## Reference Isuees

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-06-14 10:04 UTC, at-mailuong commented
LGTM

2018-06-26 07:18 UTC, at-mailuong commented
LGTM

2018-07-09 07:56 UTC, ghost requested changes

2018-07-09 07:56 UTC, at-huenguyen commented on tests/Feature/Api/CommentApiTest.php
> +     * @dataProvider listStructureTest
title comment đâu em?

2018-07-09 09:35 UTC, ghost approved these changes

2018-07-09 09:35 UTC, merged