Add layout edit profile
AT-PHPIntership/product-tiki pull request #172
Opened 2018-06-18 09:17 UTC by at-khadinh

## Description
Add layout edit profile.
## Reference Requirements

## Reference Isuees

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-06-18 09:21 UTC, at-phuongvu commented on resources/views/public/pages/profile.blade.php
> +                                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="fullname">{{ __('user.index.fullname') }}<span class="required">{{ __('user.index.requied') }}</span></
sửa lại `for` này

2018-06-19 02:04 UTC, ghost approved these changes

2018-06-19 02:05 UTC, ghost requested changes

2018-06-19 02:05 UTC, at-huenguyen commented on resources/views/public/pages/profile.blade.php
> +                    <a class="btn btn-success" data-toggle="modal" data-target="#edit_profile"><i class="fa fa-edit m-right-xs"></i>Edit Profile</a>
`Edit Profile` hardcode nha em

2018-06-19 05:03 UTC, ghost approved these changes

2018-06-19 05:03 UTC, merged