Create category
AT-PHPIntership/product-tiki pull request #19
Opened 2018-05-16 08:52 UTC by at-trangle

## Description
validate and create new category
## Reference Requirements

## Reference Isuees

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)
`mysql> explain select * from `categories` where parent_id is null\G;
*************************** 1. row ***************************
           id: 1
  select_type: SIMPLE
        table: categories
   partitions: NULL
         type: ALL
possible_keys: NULL
          key: NULL
      key_len: NULL
          ref: NULL
         rows: 24
     filtered: 10.00
        Extra: Using where
1 row in set, 1 warning (0.00 sec)

ERROR: 
No query specified
`
`

2018-05-16 10:11 UTC, at-phuongvu commented on resources/views/admin/pages/categories/create.blade.php
> +                  <input type="text" class="form-control" placeholder="Name Category" name="name">
placeholder cũng có `@lang`

2018-05-20 03:40 UTC, ghost requested changes

2018-05-20 03:40 UTC, at-huenguyen commented on app/Http/Controllers/Admin/CategoryController.php
> +        $category = new Category();
em ko cần viết như vại.
Em có thể tham khảo như vại, để tạo Category mới:
```
$input = $request->all();
Category::insert($input);
```

2018-05-20 03:40 UTC, at-huenguyen commented on app/Http/Controllers/Admin/CategoryController.php
> +        if ($category->save()) {
muốn tạo 1 Category mới, em ko xem thử nó có bị `trùng tên` hay ko à?
(có thể nghĩ thêm các case khác nếu có)

2018-05-20 03:40 UTC, at-huenguyen commented on app/Http/Controllers/Admin/CategoryController.php
> +use App\Http\Requests\Backend\CategoryRequest;
class `CategoryRequest` sao ko thaays trong nhánh của em?

2018-05-20 03:40 UTC, at-huenguyen commented on app/Http/Controllers/Admin/CategoryController.php
> +            return view('admin.pages.categories.create');
nếu tạo fail thì có thông báo gì để biết ko?

2018-05-21 04:10 UTC, at-trangle commented on app/Http/Controllers/Admin/CategoryController.php
> +        if ($category->save()) {
cái này e có validate r à chị

2018-05-23 03:45 UTC, at-trangle commented on app/Http/Controllers/Admin/CategoryController.php
> +            return view('admin.pages.categories.create');
e thấy nếu tạo fail thì có message validate rồi mà chị

2018-05-23 03:51 UTC, at-trangle commented on app/Http/Controllers/Admin/CategoryController.php
> +        if ($category->save()) {
dạ e đã fix r chị

2018-05-23 09:00 UTC, ghost approved these changes

2018-05-24 01:51 UTC, merged