Admin list and show user
AT-PHPIntership/product-tiki pull request #20
Opened 2018-05-16 10:06 UTC by at-mailuong

## Description
get list, show user and user_info, paginage list user 
## Reference Requirements

## Reference Isuees

## Migrations
NO

## Impacted Areas in Application

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

`
mysql> explain select users.*, user_info.* from users inner join user_info on users.id = user_info.user_id\G;
*************************** 1. row ***************************
           id: 1
  select_type: SIMPLE
        table: user_info
   partitions: NULL
         type: ALL
possible_keys: user_info_user_id_foreign
          key: NULL
      key_len: NULL
          ref: NULL
         rows: 10
     filtered: 100.00
        Extra: NULL
*************************** 2. row ***************************
           id: 1
  select_type: SIMPLE
        table: users
   partitions: NULL
         type: eq_ref
possible_keys: PRIMARY
          key: PRIMARY
      key_len: 4
          ref: product_tiki.user_info.user_id
         rows: 1
     filtered: 100.00
        Extra: NULL
2 rows in set, 1 warning (0.00 sec)
`

2018-05-16 10:16 UTC, at-trangle commented on resources/views/admin/pages/users/index.blade.php
> +                @endif
cái ni nên để @lang

2018-05-16 10:17 UTC, at-trangle commented
cái comment của PR nên để explain \G á

2018-05-17 02:37 UTC, ghost requested changes

2018-05-17 02:37 UTC, at-huenguyen commented on database/factories/UserInfoFactory.php
> +        'user_id' => App\Models\User::all()->unique()->random()->id,
`user_id` này, em ko nên để luôn trong `factory`. Vì sau này em có thể dùng nó trong unit test hay gì khác, `user_id` mình sẽ truyền theo mong muốn của mình

2018-05-17 02:37 UTC, at-huenguyen commented on database/seeds/UserInfoTableSeeder.php
> +        factory('App\Models\UserInfo', 10)->create();
sử dụng random userIds ở factory bỏ qua đây dùng nha

2018-05-17 06:39 UTC, ghost requested changes

2018-05-17 06:39 UTC, at-huenguyen commented on database/factories/UserInfoFactory.php
> +        'user_id' => $faker->unique()->randomElement(User::pluck('id')->toArray()),
remove `user_id` here, plz

2018-05-17 09:54 UTC, at-huenguyen commented on tests/Browser/Pages/Users/TestShowListUser.php
> +                    ->assertSee('Laravel');
test chỉ có vại thôi à em?

2018-05-17 10:25 UTC, at-huenguyen commented on database/factories/UserInfoFactory.php
> +        'identity_card' => $faker->numberBetween($min = 1000000000, $max = 999999999),
`identity_card` này riêng cho từng user thì em cũng nên cho `unique` cho nó nhá

2018-05-21 04:26 UTC, at-huenguyen commented on 2018-05-21-03-38-09.078-VBoxSVC-4298.log
> +Log created: 2018-05-21T03:38:09.786060000Z
file này làm gì đây em?

2018-05-21 04:26 UTC, at-huenguyen commented on database/seeds/UserInfoTableSeeder.php
> +        for ($i =0 ;$i < 10; $i++) {
viết lại như naỳ nha em `for ($i = 0; $i < 10; $i++) {`

2018-05-21 04:33 UTC, at-mailuong commented on 2018-05-21-03-38-09.078-VBoxSVC-4298.log
> +Log created: 2018-05-21T03:38:09.786060000Z
cái đó chắc do em mới cài apache nó tự sinh đấy chị để em xóa

2018-05-21 04:33 UTC, at-huenguyen commented on resources/views/admin/pages/users/index.blade.php
> +                <td class="a-right a-right ">{{ __('user.index.female') }}</td>
lùi vào `2 spaces` nha em

2018-05-21 04:33 UTC, at-huenguyen commented on resources/views/admin/pages/users/index.blade.php
>                <tr class="even pointer">
chỗ này cũng lùi vào 2 spaces

2018-05-21 04:33 UTC, at-huenguyen commented on resources/views/admin/pages/users/index.blade.php
> +                <td class="a-right a-right ">{{ __('user.index.male') }}</td>
lùi vào nha

2018-05-21 10:50 UTC, ghost approved these changes

2018-05-21 10:50 UTC, merged