[Admin] Add create product, upload product image
AT-PHPIntership/product-tiki pull request #21
Opened 2018-05-16 17:15 UTC by at-khadinh

## Description
Add create product, and upload product image.
## Reference Requirements

## Reference Isuees

## Migrations
YES

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-05-17 06:36 UTC, ducxinh-dn-201 commented on app/Http/Controllers/Admin/ProductController.php
> +        ]));
em tạo file PostProductRequest để validate các dữ liệu đưa lên.
với dùng `fillable` trong model `product` để chỉ ra các trường nào có thể insert vào database.
k cần phải liệt kê tất cả các trường ở đây đâu em

2018-05-17 06:39 UTC, ducxinh-dn-201 commented on app/Http/Controllers/Admin/ProductController.php
> +        }
đoạn này em xử lý phía trên `line 47` lun nha. chứ mắc công 2 lần truy xuất `database`

2018-05-17 06:42 UTC, ducxinh-dn-201 commented on app/Http/Controllers/Admin/ProductController.php
> +        $product = Product::create(request([
$request->status = $product->quantity ? true : false

2018-05-17 06:43 UTC, ducxinh-dn-201 commented on app/Http/Controllers/Admin/ProductController.php
> +        $img->move('images/upload', $imgName);
move  `images/upload` vào `define` file em nhé

2018-05-17 06:44 UTC, ducxinh-dn-201 commented on app/Http/Controllers/Admin/ProductController.php
> +        session()->flash('message', 'Create product successfully');
trans `Create product successfully`

2018-05-17 06:45 UTC, ducxinh-dn-201 commented on resources/views/admin/pages/products/create.blade.php
> +          <form id="demo-form2" data-parsley-validate method="POST" action="/admin/products" enctype="multipart/form-data" class="form-horizontal form-label-left">
dùng `route` chỗ `action` thay vì `hard url` vào em nhé

2018-05-17 06:45 UTC, ducxinh-dn-201 commented on resources/views/admin/pages/products/create.blade.php
> +                  @foreach ( $categories as $category )
sau `(` k có space e

2018-05-17 06:45 UTC, ducxinh-dn-201 commented on resources/views/admin/layout/message.blade.php
> +@if(Session::has('message'))
sau @if có 1 `space`

2018-05-17 06:47 UTC, ducxinh requested changes
please check my cmt

2018-05-18 06:35 UTC, ghost approved these changes
LGTM

2018-05-18 06:35 UTC, merged