[admin] delete product
AT-PHPIntership/product-tiki pull request #31
Opened 2018-05-18 11:05 UTC by at-khadinh

## Description
Add delete product layout, soft delete product
## Reference Requirements

## Reference Isuees

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-05-22 02:42 UTC, at-xinhnguyen commented on resources/views/admin/pages/products/index.blade.php
> +                        <button type="submit"><i class="fa fa-trash"></i></button>
chuyển button sang màu đỏ em nhé:

2018-05-22 02:46 UTC, at-xinhnguyen commented on app/Http/Controllers/Admin/ProductController.php
> +        $product = Product::findOrFail($id);
dùng try catch để trả về `session flash` thông báo lỗi nếu có.
vì có thể user truyền `id` ảo

2018-05-22 02:46 UTC, ghost requested changes
Pleae check my cmt

2018-05-23 08:37 UTC, xinh-ds commented on app/Http/Controllers/Admin/ProductController.php
> +            return back();
dư `return` rồi nè em.. dùng cái ngoài dùng đc rồi

2018-05-23 08:37 UTC, xinh-ds commented on app/Http/Controllers/Admin/ProductController.php
> +        $product->delete();
line này move vào trong try { ...} em nhé

2018-05-23 08:38 UTC, xinh-ds commented on app/Http/Controllers/Admin/ProductController.php
> +            return back();
dư return rồi nè em.. dùng cái ngoài dùng đc rồi

2018-05-23 08:38 UTC, xinh-ds commented on app/Http/Controllers/Admin/ProductController.php
> +        $product->delete();
line này move vào trong try { ...} em nhé

2018-05-23 08:38 UTC, at-xinhnguyen commented on app/Http/Controllers/Admin/ProductController.php
> +            return back();
dư return rồi nè em.. dùng cái ngoài dùng đc rồi

2018-05-23 08:39 UTC, at-xinhnguyen commented on app/Http/Controllers/Admin/ProductController.php
> +        $product->delete();
dư return rồi nè em.. dùng cái ngoài dùng đc rồi

2018-05-23 08:39 UTC, at-xinhnguyen commented on app/Http/Controllers/Admin/ProductController.php
> +            return back();
dùng cái `return back` ở dưới đc rồi em

2018-05-23 09:07 UTC, ghost approved these changes
LGTM

2018-05-23 09:07 UTC, merged