Update category
AT-PHPIntership/product-tiki pull request #38
Opened 2018-05-21 08:28 UTC by at-trangle

## Description
Update category and update list categories in index page
## Reference Requirements

## Reference Isuees
#{issue_id}

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

mysql> explain select * from `categories` where `categories`.`id` = '17' limit 1\G;
*************************** 1. row ***************************
           id: 1
  select_type: SIMPLE
        table: categories
   partitions: NULL
         type: const
possible_keys: PRIMARY
          key: PRIMARY
      key_len: 4
          ref: const
         rows: 1
     filtered: 100.00
        Extra: NULL
1 row in set, 1 warning (0.00 sec)
select * from `categories` where `parent_id` is null
 explain update categories set parent_id = 3, name = 'Mai', updated_at= '2018-05-21 08:25:55' where id= 17\G;
*************************** 1. row ***************************
           id: 1
  select_type: UPDATE
        table: categories
   partitions: NULL
         type: range
possible_keys: PRIMARY
          key: PRIMARY
      key_len: 4
          ref: const
         rows: 1
     filtered: 100.00
        Extra: Using where
1 row in set (0.00 sec)

2018-05-22 01:31 UTC, at-phuongvu commented on resources/views/admin/pages/categories/index.blade.php
> +                  <td class="last "><a href="/admin/categories/{{$list->id}}/edit"><i class="fa fa-edit"></i></a> | <a href=""><i class="fa fa-trash"></i></a>
dùng route chứ ko truyền thẳng link nha ... `{{ route('admin.categories.edit', ['id'] => $list->id  }}`
sửa mấy chỗ khác luôn nghe để sau sửa route lại nhưng name như cũ thì ko phải chỉnh lại khắp nơi

2018-05-24 09:12 UTC, ghost requested changes

2018-05-28 16:34 UTC, at-huenguyen commented on app/Http/Controllers/Admin/CategoryController.php
> +        $category = Category::find($id);
em xem có cần `try catch` hay `if else` chỗ này, vì nếu ko tìm thấy category theo id thì sao?

2018-05-29 03:38 UTC, at-trangle commented on app/Http/Controllers/Admin/CategoryController.php
> +        $category = Category::find($id);
cái ni e đã if else ở dưới r mà chị. Nếu save đc thì redirect về trang index, còn fail tức là cả đoạn trên đã fail r mà chị (back() trang hiện tại ạ)

2018-05-29 05:04 UTC, at-phuongvu commented
LGTM

2018-05-30 02:13 UTC, ghost requested changes

2018-05-30 02:13 UTC, at-vietpham commented on app/Http/Controllers/Admin/CategoryController.php
> +        try {
Đoạn `try` này em dùng để bắt trường hợp lỗi nào?

2018-05-30 02:13 UTC, at-vietpham commented on app/Http/Requests/Backend/EditCategoryRequest.php
> +            'name' => 'required'
Rule này có khác với rule bên create category không?

2018-05-30 02:13 UTC, at-vietpham commented on app/Http/Controllers/Admin/CategoryController.php
> +    public function update(EditCategoryRequest $request, $id)
Đoạn này dùng binding model
`public function update(EditCategoryRequest $request, Category $category)`
https://laravel.com/docs/5.6/routing#implicit-binding

2018-05-30 02:13 UTC, at-vietpham commented on resources/views/admin/pages/categories/edit.blade.php
> +                    <option value="">Null</option>
Text `Null` nghĩa là sao vậy?

2018-05-30 02:13 UTC, at-vietpham commented on resources/views/admin/pages/categories/edit.blade.php
> +                  <a href="{{ route('admin.categories.index') }}" class="btn btn-success">Back</a>
Text phải được gọi từ file lang.

2018-05-30 02:13 UTC, at-vietpham commented on app/Http/Controllers/Admin/CategoryController.php
>  use App\Http\Requests\Backend\CategoryRequest;
Nếu dùng dùng class này thì không `use`

2018-05-30 02:19 UTC, at-trangle commented on app/Http/Controllers/Admin/CategoryController.php
> +        try {
đoạn try này e bắt trường hơp find đc $id hay không ạ

2018-05-30 02:27 UTC, at-trangle commented on app/Http/Controllers/Admin/CategoryController.php
> +    public function update(EditCategoryRequest $request, $id)
chỗ này team e dùng id hết à a

2018-05-30 02:27 UTC, at-trangle commented on resources/views/admin/pages/categories/edit.blade.php
> +                    <option value="">Null</option>
null này là không có danh mục cha ạ

2018-05-30 02:29 UTC, at-trangle commented on app/Http/Requests/Backend/EditCategoryRequest.php
> +            'name' => 'required'
dạ có khác, bên create thì có unique:categories nữa để check trùng vs category đã tạo, còn bên update có thể giữ name cx và thay đổi parent category

2018-05-30 02:32 UTC, at-trangle commented on app/Http/Controllers/Admin/CategoryController.php
>  use App\Http\Requests\Backend\CategoryRequest;
không use nó báo lỗi a

2018-05-30 02:32 UTC, at-trangle commented on resources/views/admin/pages/categories/edit.blade.php
> +                  <a href="{{ route('admin.categories.index') }}" class="btn btn-success">Back</a>
dạ cái ni để e fix

2018-05-30 02:35 UTC, at-vietpham commented on app/Http/Requests/Backend/EditCategoryRequest.php
> +            'name' => 'required'
Thế vì sao update lại ko để rule đó. Nếu vậy thì lúc update anh cho trùng tên được rồi?

2018-05-30 02:35 UTC, at-vietpham commented on resources/views/admin/pages/categories/edit.blade.php
> +                    <option value="">Null</option>
Null không có những là danh mục cha.

2018-05-30 02:37 UTC, at-vietpham commented on app/Http/Controllers/Admin/CategoryController.php
> +    public function update(EditCategoryRequest $request, $id)
Vậy thì sau này chổ dùng binding model được thì đổi lại hết.

2018-05-30 02:37 UTC, at-trangle commented on app/Http/Requests/Backend/EditCategoryRequest.php
> +            'name' => 'required'
a update mà vẫn muốn giữ tên cũ, chỉ muốn thay đổi danh mục cha không thì sao a?

2018-05-30 02:38 UTC, at-trangle commented on resources/views/admin/pages/categories/edit.blade.php
> +                    <option value="">Null</option>
dạ ok để e fix cái này

2018-05-30 02:41 UTC, at-trangle commented on app/Http/Controllers/Admin/CategoryController.php
> +    public function update(EditCategoryRequest $request, $id)
da. cái này để e nói lại team

2018-05-30 03:16 UTC, at-vietpham commented on app/Http/Requests/Backend/EditCategoryRequest.php
> +            'name' => 'required'
Thì em phải config để loại trừ chính nó chứ.

2018-05-30 06:45 UTC, ghost requested changes

2018-05-30 06:53 UTC, at-trangle commented on app/Http/Controllers/Admin/CategoryController.php
> +            $category->level = 0;
cái này e có để default là 0 rồi.để e sửa lại mấy chỗ review r e push lên lại

2018-05-30 07:30 UTC, ghost requested changes

2018-05-30 07:30 UTC, at-vietpham commented on resources/views/admin/pages/categories/edit.blade.php
> +                    @foreach ($categories as $cats)
`$cats` nghĩa là gì? đặt là `$parentCategory`

2018-05-30 07:30 UTC, at-vietpham commented on resources/views/admin/pages/categories/edit.blade.php
> +            @include('admin.layout.errors')
Lùi vào 1 tab

2018-05-30 07:51 UTC, at-vietpham commented
LGTM 🏭

2018-05-30 07:51 UTC, merged