Delete category
AT-PHPIntership/product-tiki pull request #39
Opened 2018-05-21 08:47 UTC by at-trangle

## Description
delete category
## Reference Requirements

## Reference Isuees

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

mysql> explain delete from `categories` where `parent_id` = 18 \G;
*************************** 1. row ***************************
           id: 1
  select_type: DELETE
        table: categories
   partitions: NULL
         type: ALL
possible_keys: NULL
          key: NULL
      key_len: NULL
          ref: NULL
         rows: 13
     filtered: 100.00
        Extra: Using where
1 row in set (0.00 sec)

2018-05-25 03:09 UTC, at-huenguyen commented on app/Http/Controllers/Admin/CategoryController.php
> +    public function destroy($id)
hàm xóa category, cách thực hiện sẽ như nào em?

2018-05-29 07:41 UTC, at-phuongvu commented
LGTM

2018-05-30 08:19 UTC, ghost requested changes

2018-05-30 08:19 UTC, at-vietpham commented on app/Models/Category.php
> +    protected $dates = ['deleted_at'];
Vì sao lại phải thêm `deleted_at` vào `dates`

2018-05-30 08:19 UTC, at-vietpham commented on public/js/deleteCategory.js
> +  msg = "Do you want to delete Category Id= " + id;
Message phải được gọi từ file lang

2018-05-30 08:27 UTC, at-vietpham commented on app/Models/Category.php
> +    protected $dates = ['deleted_at'];
Không cần cho vào vẫn dùng soft delete được mà?

2018-05-30 08:43 UTC, at-vietpham commented
LGTM 💴

2018-05-30 08:43 UTC, merged