Test create categoy
AT-PHPIntership/product-tiki pull request #42
Opened 2018-05-22 02:44 UTC by at-trangle

## Description
Test create categoy
## Reference Requirements

## Reference Isuees

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

2018-05-22 02:49 UTC, at-phuongvu commented on resources/views/admin/pages/categories/create.blade.php
> +            <form class="form-horizontal form-label-left" method="post" action="/admin/categories">
action cũng dùng route

2018-05-22 04:53 UTC, at-phuongvu commented on app/Http/Controllers/Admin/CategoryController.php
> +            $data['msg'] = 'Create Category successfull!';
`@lang` nè

2018-05-29 04:33 UTC, at-phuongvu commented
LGTM

2018-05-29 04:33 UTC, at-trangle commented on tests/Browser/Admin/CreateCategoryTest.php
> +                ->select('parent_id', '1');
chỗ này e tạo factory 1 cái category thì cái vừa tạo id là 1 chứ gì chị ?

2018-05-30 08:48 UTC, at-phuongvu commented on tests/Browser/Admin/CreateCategoryTest.php
> +                ->type('name', null);
không cần type null

2018-05-30 08:52 UTC, at-trangle commented on tests/Browser/Admin/CreateCategoryTest.php
> +                ->type('name', null);
ok để mình fix bạn

2018-05-30 10:10 UTC, ghost requested changes

2018-05-30 10:10 UTC, at-vietpham commented on tests/Browser/Admin/CreateCategoryTest.php
> +    public function testCategoryValidateForInput()
Dùng dataProvider. Tham khảo ở đây: https://github.com/AT-PHPIntership/borrow-book/blob/master/tests/Browser/Pages/Backend/CreateUserTest.php#L47

2018-05-31 07:08 UTC, at-phuongvu commented on tests/Browser/Admin/CreateCategoryTest.php
> +                ->select('parent_id', null);
ko select thì nó là null mà đúng ko ?

2018-05-31 07:09 UTC, at-trangle commented on tests/Browser/Admin/CreateCategoryTest.php
> +                ->select('parent_id', null);
uh, để mình fix luôn

2018-05-31 07:42 UTC, ghost requested changes

2018-05-31 07:42 UTC, at-vietpham commented on tests/Browser/Admin/CreateCategoryTest.php
> +    public function testCreatesCategoryWithExistCategory()
Dùng dataProvider ở test này.

2018-05-31 21:05 UTC, at-phuongvu commented on tests/Browser/Admin/CreateCategoryTest.php
> +                    ->type('name', 'Iphone');
chỗ này t nghĩ có thể sử dụng `$content` nè ...

2018-05-31 21:16 UTC, at-phuongvu commented on tests/Browser/Admin/CreateCategoryTest.php
> +    public function listCaseTestValidateForInputExist()
ghép thành 1 `dataProvider` thử đi ...

2018-06-01 06:35 UTC, ghost requested changes
plz check my cmts

2018-06-01 08:50 UTC, at-phuongvu commented on tests/Browser/Admin/CreateCategoryTest.php
> +            ['name', 'Iphone', 'The name has already been taken.'],
chỗ này em nói bạn ấy ghép vào ấy ạ :"< do em thấy 2 cái test nó hành động tương tự nhau cùng kiểu test thì mình cần chung 1 test case là được rồi chứ ạ

2018-06-01 09:28 UTC, at-trangle commented on tests/Browser/Admin/CreateCategoryTest.php
> +        factory('App\Models\Category', 1)->create([
chỗ này e tạo để check cái `$content` trùng với cái `category` tạo ra á chị

2018-06-04 02:50 UTC, at-huenguyen commented on tests/Browser/Admin/CreateCategoryTest.php
> +            ['name', 'Iphone', 'The name has already been taken.'],
1 test em cần phải tạp `category` trc khi thực hiện hành động test mà

2018-06-04 04:00 UTC, at-vietpham commented
LGTM 📦

2018-06-04 04:00 UTC, merged