Test update category
AT-PHPIntership/product-tiki pull request #44
Opened 2018-05-22 10:02 UTC by at-trangle

## Description
Test update category
## Reference Requirements

## Reference Isuees

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

2018-05-31 21:22 UTC, at-phuongvu commented on tests/Browser/UpdateCategoryTest.php
> +            $browser->visit('/admin/categories/' . $category->id . '/edit')
sao không test từ `click` luôn mà gọi thẳng đường link thế

2018-05-31 21:22 UTC, at-phuongvu commented on tests/Browser/UpdateCategoryTest.php
> +    public function listCaseTestValidateForInputExist()
có thể dùng chung 1 `dataProvider` được không ? vì t thấy mấy method gần như hành động giống nhau rồi ...

2018-05-31 21:22 UTC, at-phuongvu commented on tests/Browser/UpdateCategoryTest.php
> +        $categoryOther = Category::find(3);
`$categoryOther = factory('App\Models\Category') -> create([ ... ]);`

2018-06-04 04:57 UTC, ghost requested changes

2018-06-04 04:57 UTC, at-vietpham commented on tests/Browser/Admin/UpdateCategoryTest.php
> +}
Thêm các case cho những trường hợp như update category nhưng chọn parent lại là category con của mình.

2018-06-04 05:00 UTC, at-trangle commented on tests/Browser/Admin/UpdateCategoryTest.php
> +}
cái này e đã xử lý ở hàm edit r a. e chỉ cho chọn những thèn cùng cấp, và cha trở lên thôi ạ

2018-06-04 05:21 UTC, closed without merging