upload migration file
AT-PHPIntership/product-tiki pull request #5
Opened 2018-05-14 07:00 UTC by at-mailuong

## Description
A few sentences describing the overall goals of the pull request's commits.
## Reference Requirements
- Task ID: TI-1

## Reference Isuees
#2 

## Migrations
YES 
## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
- No SQL

2018-05-14 08:08 UTC, at-xinhnguyen commented on database/migrations/2014_10_12_000000_create_users_table.php
> +            $table->string('username',100)->unique();
please add 1 `space after `,`

2018-05-14 08:14 UTC, at-xinhnguyen commented on composer.lock
> -        "Read more about it at https://getcomposer.org/doc/01-basic-usage.md#composer-lock-the-lock-file",
fail CI rồi em, khi nào thêm package thì hẳn push file này lên em nhé

2018-05-14 09:46 UTC, at-xinhnguyen commented on database/migrations/2018_05_10_084045_create_orderdetails_table.php
> +        Schema::dropIfExists('invoices');
trên `order_details ` dưới cũng same lun em

2018-05-14 09:55 UTC, at-xinhnguyen commented on database/migrations/2018_05_10_083714_create_images_table.php
> +            $table->softDeletes('deleted_at');
images a nghĩ mình xoá cứng lun k  cần soft delete đâu em

2018-05-14 09:56 UTC, at-xinhnguyen commented on database/migrations/2018_05_10_084833_create_posts_table.php
> +            $table->text('content')->charset('utf8')->collation('utf8_unicode_ci');
text mình cho `nullable` đi em, vì có thể user chỉ review mà để rỗng `content`

2018-05-14 09:56 UTC, at-xinhnguyen commented on database/migrations/2018_05_10_084833_create_posts_table.php
> +            $table->boolean('type');
em thêm `comment` cho trường type và để default hoặc nullable nhé

2018-05-14 10:03 UTC, at-xinhnguyen commented on database/migrations/2018_05_10_085527_create_userinfo_table.php
> +            $table->boolean('gender')->default(0);
em thêm comment cho trường `gender` nhé  1: male: 2: female
=> $table->boolean('gender')->default(0)->comment('1: male, 2: female');

2018-05-14 10:04 UTC, at-xinhnguyen commented on database/migrations/2014_10_12_000000_create_users_table.php
> +            $table->timestamp('last_logined_at');
nullable trường này em nhé

2018-05-14 10:04 UTC, at-xinhnguyen commented on database/migrations/2014_10_12_000000_create_users_table.php
> +            $table->string('api_token', 60);
nullable em nhé

2018-05-14 10:05 UTC, ghost requested changes
Please check my cmt

2018-05-14 10:15 UTC, at-mailuong commented on database/migrations/2014_10_12_000000_create_users_table.php
> +            $table->string('api_token', 60);
đã check hết rồi a

2018-05-15 02:28 UTC, ghost approved these changes
LGTM

2018-05-15 02:41 UTC, merged