Admin validate and create user
AT-PHPIntership/product-tiki pull request #51
Opened 2018-05-23 05:47 UTC by at-mailuong

## Description
validate and create save user
## Reference Requirements

## Reference Isuees

## Migrations
YES 

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`

`explain insert into `users` (`username`, `email`, `password`, `updated_at`, `created_at`) values ("gdhfhfj", "dhh@gmail.com", "$2y$10$kgj8jC8QLmXuquqvt21zCeU9lhlu48/k2f9KD65F3kcfpt3ra9kPy", "2018-05-23 05:05:09", "2018-05-23 05:05:09")\G`

> *************************** 1. row ***************************
>            id: 1
>   select_type: INSERT
>         table: users
>    partitions: NULL
>          type: ALL
> possible_keys: NULL
>           key: NULL
>       key_len: NULL
>           ref: NULL
>          rows: NULL
>      filtered: NULL
>         Extra: NULL
> 1 row in set (0.00 sec)

`explain insert into `user_info` (`user_id`, `full_name`, `address`, `phone`, `identity_card`, `dob`, `avatar`, `updated_at`, `created_at`) values (36, "sdfhfjgj", "hfjgfgrewrwe", "2412412412", "123123123", "2018-05-04", null, "2018-05-23 05:05:09", "2018-05-23 05:05:09")\G`

> *************************** 1. row ***************************
>            id: 1
>   select_type: INSERT
>         table: user_info
>    partitions: NULL
>          type: ALL
> possible_keys: NULL
>           key: NULL
>       key_len: NULL
>           ref: NULL
>          rows: NULL
>      filtered: NULL
>         Extra: NULL
> 1 row in set (0.00 sec)
>

2018-05-23 07:52 UTC, at-trangle commented on app/Http/Controllers/Admin/UserController.php
> +    }
làm thêm trường hợp tạo fail cx có message nữa

2018-05-23 08:00 UTC, at-trangle commented on resources/views/admin/pages/users/show.blade.php
>                </div>
chỗ nào có thể viết gọn hơn á Mai
`<input type="text" class="form-control" readonly="readonly" placeholder=" `
`@if ( $result->userInfo['gender'] == 1) {{ __('user.index.female') }}` 
`@else {{ __('user.index.male') }}` 
 `@endif ">`
hoặc có thể sử dụng cái viết gọn if...mà cái nớ t nghĩ k ra.. nghĩ được chỉ vs :+1:

2018-05-25 03:01 UTC, ghost requested changes

2018-05-25 03:01 UTC, at-huenguyen commented on app/Http/Controllers/Admin/UserController.php
> +        $user = new User;
em lấy riêng 1 mảng để tạo user rồi create:
```
$userData = [
    'username' => ....
.....
];
$user = User::create($userData);```

2018-05-25 03:01 UTC, at-huenguyen commented on app/Http/Controllers/Admin/UserController.php
> +        $userInfo = new UserInfo;
`UserInfo` làm tương tự như trên

2018-05-25 03:01 UTC, at-huenguyen commented on app/Http/Controllers/Admin/UserController.php
> +        if ($request->gender) {
hình như ko cần phải check đâu em. Nếu ko có thì nó sẽ null

2018-05-25 03:01 UTC, at-huenguyen commented on app/Http/Controllers/Admin/UserController.php
> +        if ($request->hasFile('avatar')) {
chỗ `if .. else` này em chỉ cần xét cho biến avatar thôi, còn `create (hay save) `đặt ở ngoài

2018-05-25 06:56 UTC, at-huenguyen commented on app/Http/Controllers/Admin/UserController.php
> +            $image->move($destinationPath, $nameNew);
em có thể xét nếu `create user info` thành công thì mới tạo file ảnh nha

2018-05-25 08:03 UTC, ghost approved these changes
LGTM

2018-05-25 08:22 UTC, merged