Show parent category
AT-PHPIntership/product-tiki pull request #54
Opened 2018-05-23 09:52 UTC by at-trangle

## Description
A few sentences describing the overall goals of the pull request's commits.
Show child category and grand category
- Task ID: TI-1

## Reference Isuees

## Migrations

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

mysql> explain select * from `categories` where `categories`.`id` = '3' limit 1\G;
*************************** 1. row ***************************
           id: 1
  select_type: SIMPLE
        table: categories
   partitions: NULL
         type: const
possible_keys: PRIMARY
          key: PRIMARY
      key_len: 4
          ref: const
         rows: 1
     filtered: 100.00
        Extra: NULL
1 row in set, 1 warning (0.00 sec)
mysql> explain select * from `categories` where `parent_id` = '3'\G;
*************************** 1. row ***************************
           id: 1
  select_type: SIMPLE
        table: categories
   partitions: NULL
         type: ALL
possible_keys: NULL
          key: NULL
      key_len: NULL
          ref: NULL
         rows: 23
     filtered: 10.00
        Extra: Using where
1 row in set, 1 warning (0.00 sec)
mysql> explain select * from `categories` where `categories`.`parent_id` in ('10', '11')\G;
*************************** 1. row ***************************
           id: 1
  select_type: SIMPLE
        table: categories
   partitions: NULL
         type: ALL
possible_keys: NULL
          key: NULL
      key_len: NULL
          ref: NULL
         rows: 23
     filtered: 20.00
        Extra: Using where
1 row in set, 1 warning (0.00 sec)
mysql> explain select * from `categories` where `categories`.`parent_id` in ('12', '13', '14', '15')\G;
*************************** 1. row ***************************
           id: 1
  select_type: SIMPLE
        table: categories
   partitions: NULL
         type: ALL
possible_keys: NULL
          key: NULL
      key_len: NULL
          ref: NULL
         rows: 23
     filtered: 40.00
        Extra: Using where
1 row in set, 1 warning (0.00 sec)

2018-05-24 02:02 UTC, at-phuongvu commented on resources/views/admin/pages/categories/show.blade.php
> +<link href="/css/show.css" rel="stylesheet">
nên `@yield` 1 phần custom css ở trong `head` rồi ở đây gọi ra chứ thế này là đưa css vào thẳng body rồi nè ...

2018-05-24 03:12 UTC, ghost requested changes
plz check cmts

2018-05-24 03:12 UTC, at-huenguyen commented on app/Http/Controllers/Admin/CategoryController.php
> +        $itemCategory = Category::find($id);
em truy vấn ```Category::find($id)->with(....```
nó đã lấy lun phần `itemCategory` của em trong đó nữa mà, nên đâu cần phải 2 câu truy vấn vại

2018-05-24 03:12 UTC, at-huenguyen commented on app/Http/Controllers/Admin/CategoryController.php
> +            return $query->with('categories');
em chỉ xử lí vại thì chỉ cần ```Category::find($id)->with('categories')->where(...``` 
là đủ rồi

2018-05-24 03:12 UTC, at-huenguyen commented on app/Models/Category.php
> +    /**
giưã 2 function cần 1 hàng nha em, **ko mắc lỗi này nữa nhá**
chú ý check lại PR của mình sau khi fix nha.

2018-05-24 03:12 UTC, at-huenguyen commented on resources/views/admin/pages/categories/show.blade.php
> +<link href="/css/show.css" rel="stylesheet">
ko nên bỏ thẳng link đây như vại nha em

2018-05-24 03:15 UTC, at-trangle commented on app/Models/Category.php
> +    /**
ok chị

2018-05-24 03:34 UTC, at-trangle commented on app/Http/Controllers/Admin/CategoryController.php
> +        $itemCategory = Category::find($id);
chỗ này e dd ra thì cái `Category::find($id)->with(....` nó k chưa cái itemCategory nên e mới query thêm à chị

2018-05-24 03:59 UTC, at-huenguyen commented on app/Http/Controllers/Admin/CategoryController.php
> +        $itemCategory = Category::find($id);
nhưng nó đã có các cột giống trong $itemCategory phải ko em?

2018-05-24 04:07 UTC, at-trangle commented on app/Http/Controllers/Admin/CategoryController.php
> +        $itemCategory = Category::find($id);
dạ k chị...nó chỉ lấy đc các child category của itemCategory thôi chị

2018-05-24 05:03 UTC, at-huenguyen commented on app/Http/Controllers/Admin/CategoryController.php
> +        $itemCategory = Category::find($id);
ok em

2018-05-24 05:04 UTC, at-huenguyen commented on app/Models/Category.php
> +    /**
@at-trangle quên lại rồi nhá ✌️

2018-05-25 02:29 UTC, ghost approved these changes

2018-05-25 02:54 UTC, merged