Admin send mail create user
AT-PHPIntership/product-tiki pull request #59
Opened 2018-05-27 03:22 UTC by at-mailuong

## Description
send mail create user success
## Reference Requirements

## Reference Isuees

## Migrations
NO

## Impacted Areas in Application

## SQL query and `explain`

2018-05-28 02:00 UTC, at-trangle commented on resources/views/admin/pages/users/mail.blade.php
> +<p>Password: {{$password}}</p>
nhớ 1 space trước và sau {{ $email }} nghe

2018-05-29 06:45 UTC, ghost requested changes

2018-05-29 06:45 UTC, at-huenguyen commented on app/Http/Controllers/Admin/UserController.php
> +                $image = null;
đoạn else này em gán `$image` là gì vại em?

2018-05-29 06:45 UTC, at-huenguyen commented on app/Http/Controllers/Admin/UserController.php
> +                $destinationPath = public_path('/images/avatar/');
đường dẫn này `'/images/avatar/'` đặt ở config nhá em

2018-05-29 09:46 UTC, at-trangle commented
LGTM!

2018-05-30 02:33 UTC, ghost requested changes

2018-05-30 02:33 UTC, at-vietpham commented on app/Http/Controllers/Admin/UserController.php
>              $nameNew = time().'.'.$image->getClientOriginalExtension();
Tên biên nên là `$newImage`.
Nên random thêm string ở chổ này:
`$newImage = time() . '-' . str_random(8) . '.' . $image->getClientOriginalExtension();`
Đoạn này: `time().'.'.$image` nên có space cho dễ nhìn: `time() . '.' . $image`

2018-05-30 02:33 UTC, at-vietpham commented on app/Http/Controllers/Admin/UserController.php
> +        } else {
Không else ở đoạn này. 
Chỉ cần để `$newImage = ''` trước `if` là được.

2018-05-30 02:33 UTC, at-vietpham commented on app/Mail/SendMailUser.php
> +                    ->with([
Chỉ lùi 1 tab so với dòng bên trên

2018-05-30 02:33 UTC, at-vietpham commented on database/migrations/2018_05_10_085527_create_userinfo_table.php
> +            $table->boolean('gender')->nullable()->default(0)->comment('0: male, 1: female');
Không sửa lại file migration đã chạy.

2018-05-30 02:33 UTC, at-vietpham commented on resources/views/admin/pages/users/index.blade.php
> +                  @if ( $user->userInfo['is_active'] == 0 )
Pull request này cho chức năng send mail. Không update các chức năng khác ở PR này.

2018-05-30 03:46 UTC, ghost requested changes

2018-05-30 03:46 UTC, at-vietpham commented on database/migrations/2018_05_30_025929_edit_gender_user_info.php
> +<?php
file migration này không nằm trong chức năng send mail. Tách nó ra ở 1 PR khác.

2018-05-30 03:46 UTC, at-vietpham commented on database/migrations/2018_05_30_025929_edit_gender_user_info.php
> +            $table->boolean('gender')->nullable()->change();
Function `down` phải đảo ngược lại những gì `up` thực hiện

2018-05-30 04:13 UTC, at-vietpham commented
LGTM 🏒

2018-05-30 04:13 UTC, merged