upload model file
AT-PHPIntership/product-tiki pull request #6
Opened 2018-05-14 07:11 UTC by at-mailuong

## Description
A few sentences describing the overall goals of the pull request's commits.
## Reference Requirements
- Task ID: TI-1

## Reference Isuees
#2 

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`

2018-05-14 13:07 UTC, at-phuongvu commented on app/Model/MainModel.php
> +        $obj = DB::table($this->table)->where($this->name, $string)->get();
sửa chỗ này lại thành ở dưới này nè để cái đó nó chứa cái name là đc rồi 
$obj = DB::table($this->table)->where($this->name,  'like', '%'.$string.'%')->get();

2018-05-15 02:44 UTC, at-xinhnguyen commented on app/Model/Category.php
> +<?php
please rename `model folder` to `models folder`

2018-05-15 02:44 UTC, at-xinhnguyen commented on app/Model/Category.php
> +namespace App\Model\MainModel;
`namespace` should be `App\Models`

2018-05-15 02:46 UTC, at-xinhnguyen commented on app/Model/Category.php
> +    protected $table='categories';
please add 1 space after `variable` and 1 space before `value`

2018-05-15 02:47 UTC, at-xinhnguyen commented on app/Model/Category.php
> +    /**
add 1 blank line before comment

2018-05-15 02:47 UTC, at-xinhnguyen commented on app/Model/Category.php
> +    ];
add 1 blank line before comment

2018-05-15 02:51 UTC, at-xinhnguyen commented on app/Model/Category.php
> +     * Create model
description for this should be `Get the products for the category.`

2018-05-15 02:51 UTC, at-xinhnguyen commented on app/Model/Category.php
> +     * @return App\Model\Product
return type should be \Illuminate\Database\Eloquent\Relations\HasMany

2018-05-15 02:53 UTC, at-xinhnguyen commented on app/Model/Comment.php
> +     * Get Post Object
description should be `Get the post that owns the comment`

2018-05-15 02:54 UTC, at-xinhnguyen commented on app/Model/Comment.php
> +        return $this->belongsto('App\Model\Post', 'post_id', 'id');
please use `belongsTo ` instead of `belongsto`

2018-05-15 02:54 UTC, at-xinhnguyen commented on app/Model/Comment.php
> +     * @return App\Model\Post
return type should be `\Illuminate\Database\Eloquent\Relations\BelongsTo`

2018-05-15 02:58 UTC, at-xinhnguyen commented on app/Model/UserInfo.php
> +namespace App\Model\MainModel;
please use `correct namespace` : App\Models

2018-05-15 02:58 UTC, ghost requested changes
Please check my cmt

2018-05-15 04:01 UTC, at-xinhnguyen commented on app/Models/MainModel.php
> +     * @return App\Models
get của builder return về `\Illuminate\Database\Eloquent\Collection` em

2018-05-15 04:02 UTC, at-xinhnguyen commented on app/Models/MainModel.php
> +        return $obj;
a nghĩ sau này viết cái `trait`cho việc `filter`, `search`  chứ như này k mở rộng đc

2018-05-15 04:03 UTC, at-xinhnguyen commented on app/Models/User.php
> +    public function comment()
hasmany thì nên số nhiều em `comment` to `comments`

2018-05-15 04:03 UTC, at-xinhnguyen commented on app/Models/User.php
> +    public function post()
post -> posts

2018-05-15 04:04 UTC, at-xinhnguyen commented on app/Models/User.php
> +    public function order()
order -> orders

2018-05-15 04:04 UTC, at-xinhnguyen commented on app/Models/Product.php
> +    public function post()
post - > posts

2018-05-15 04:04 UTC, at-xinhnguyen commented on app/Models/Product.php
> +    public function image()
image -> images

2018-05-15 04:05 UTC, at-xinhnguyen commented on app/Models/Product.php
> +    public function orderDetail()
orderDetail -> orderDetails

2018-05-15 04:05 UTC, at-mailuong commented on app/Models/MainModel.php
> +        return $obj;
Cái này em dùng cho cái ô search bthg theo tên thôi anh còn filter chắc ko dùng tới cái này ạ. Cái này kiểu search tên sản phẩm ạ.

2018-05-15 04:30 UTC, at-xinhnguyen commented on app/Models/Post.php
> +    public function products()
BelongsTo -> `product`

2018-05-15 04:30 UTC, at-xinhnguyen commented on app/Models/Post.php
> +    public function users()
belongsTo nên số ít `users` => `user`

2018-05-15 04:38 UTC, ghost approved these changes
LGTM

2018-05-15 04:39 UTC, merged