Admin unittest create user
AT-PHPIntership/product-tiki pull request #63
Opened 2018-05-28 07:24 UTC by at-mailuong

## Description
unittest validate and create user 
## Reference Requirements

## Reference Isuees

## Migrations
YES

## Impacted Areas in Application
2018_05_10_085527_create_userinfo_table.php

## SQL query and `explain`

2018-05-29 09:06 UTC, at-trangle commented on tests/Browser/Pages/Users/ValidateAndCreateUserTest.php
> +                ->assertSee(__('user.index.createuser'));
chỗ ni để thẳng text luôn nè..trên click link nữa

2018-05-31 06:59 UTC, at-trangle commented on tests/Browser/Pages/Users/ValidateAndCreateUserTest.php
> +                ->assertSee('The username field is required.')
cái này dùng cái dataProvider nè...a mới cmt t
`https://github.com/AT-PHPIntership/borrow-book/blob/master/tests/Browser/Pages/Backend/CreateUserTest.php#L47`

2018-05-31 07:00 UTC, at-trangle commented
test thêm cho trường hợp create user đã tồn tại nữa.trong đó có test validate mấy cái như indetity_card, ... đồ nữa

2018-06-01 03:12 UTC, at-khadinh commented on tests/Browser/Pages/Users/ValidateAndCreateUserTest.php
> +             ]);
dư dấu cách nè  Mai

2018-06-01 03:12 UTC, at-khadinh commented on tests/Browser/Pages/Users/ValidateAndCreateUserTest.php
> +                    ]);
tab nhiều quá Mai

2018-06-01 03:12 UTC, at-khadinh commented on app/Http/Requests/CreateUserRequest.php
> +            'gender'         => 'required',
kiểm tra luôn trường hợp value sai luôn đi Mai. vd: value = -1

2018-06-01 09:03 UTC, ghost requested changes
check cmt nha em

2018-06-01 09:03 UTC, at-huenguyen commented on tests/Browser/Pages/Users/ValidateAndCreateUserTest.php
> +        $this->browse(function (Browser $browser) use ($name, $content, $message) {
`$content` em để toàn `''` mà ko đc sử dụng nữa thì để làm gì em
`$name` em cũng ko sử dụng, vại khai báo làm gì

2018-06-01 09:03 UTC, at-huenguyen commented on tests/Browser/Pages/Users/ValidateAndCreateUserTest.php
> +        factory('App\Models\User', 1)->create([
tạo 1 cái thì ko cần `1` nha

2018-06-01 09:03 UTC, at-huenguyen commented on tests/Browser/Pages/Users/ValidateAndCreateUserTest.php
> +    public function testValidateaAlreadyForInput($name, $content, $message)
biến `$name` ko đc dùng thì bỏ vào làm gì em?

2018-06-01 09:03 UTC, at-huenguyen commented on tests/Browser/Pages/Users/ValidateAndCreateUserTest.php
> +    public function testValidateForInput($name, $content, $message)
hàm này em test cho gì vại???
chỉ thấy nhấn `submit` và check message.
Vại nhập gì mà nó check đc cái trường hợp trên

2018-06-01 09:03 UTC, at-huenguyen commented on tests/Browser/Pages/Users/ValidateAndCreateUserTest.php
> +                ->press('Submit')
em nên thêm phần nhập cho các trường hợp chứ

2018-06-01 09:10 UTC, at-mailuong commented on tests/Browser/Pages/Users/ValidateAndCreateUserTest.php
> +    public function testValidateForInput($name, $content, $message)
hàm này em test các trường hợp không nhập gì á chị

2018-06-01 10:40 UTC, ghost reviewed
em chưa hiểu cách dùng của hàm @dataProvider rồi,
nghiên cứu đi rồi sửa lại phần test có liên quan đến @dataProvider em dùng nhá

2018-06-04 03:14 UTC, at-trangle commented on tests/Browser/Pages/Users/ValidateAndCreateUserTest.php
> +                ->clickLink(__('messages.adduser'))
chỗ ni để text 'Add User' vào luôn...tương tự ở dưới

2018-06-04 10:27 UTC, closed without merging