change create,update image, change validation create,update product
AT-PHPIntership/product-tiki pull request #77
Opened 2018-05-31 10:43 UTC by at-khadinh

## Description
Change create,update Image.
Change validation create,update product
## Reference Requirements
- Task ID: TI-1

## Reference Isuees
#{issue_id}

## Migrations
YES | NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-06-04 16:18 UTC, ghost requested changes

2018-06-04 16:18 UTC, at-huenguyen commented on resources/views/admin/pages/products/create.blade.php
> +                  <input name="input_img[]" type="file" id="imageInput" multiple>
`name="input_img[]"` là sao em?

2018-06-04 16:18 UTC, at-huenguyen commented on app/Http/Controllers/Api/ImageController.php
> +            unlink(config('define.product.upload_image_url') . $img->img_url);
như vại là ok à em, có cần thêm `public_path(...)` ko?

2018-06-04 16:18 UTC, at-huenguyen commented on app/Http/Controllers/Admin/ProductController.php
> +            array_push($imagesData, $image);
em có thể dùng 
```
$imageData[] = [
   'product_id' => $product->id,
   'img_url' => $imgName
];

2018-06-04 18:29 UTC, at-khadinh commented on resources/views/admin/pages/products/create.blade.php
> +                  <input name="input_img[]" type="file" id="imageInput" multiple>
là một mảng để chứa các image upload chị. Em dùng để upload nhiều image cùng lúc.

2018-06-04 18:30 UTC, at-khadinh commented on app/Http/Controllers/Api/ImageController.php
> +            unlink(config('define.product.upload_image_url') . $img->img_url);
dạ em để thế nó vẫn xóa được chị.

2018-06-05 02:18 UTC, at-huenguyen commented on app/Http/Controllers/Api/ImageController.php
> +            unlink(public_path() . '/' . config('define.product.upload_image_url') . $img->img_url);
bỏ vào trong public_path đc ko em,
em thử `public_path(config('define.product.upload_image_url') . $img->img_url)` xem sao

2018-06-05 02:18 UTC, at-huenguyen commented on resources/views/admin/pages/products/create.blade.php
> +                  <input name="input_img[]" type="file" id="imageInput" multiple>
ok

2018-06-05 04:12 UTC, ghost approved these changes

2018-06-05 04:12 UTC, merged