test update category
AT-PHPIntership/product-tiki pull request #88
Opened 2018-06-04 07:00 UTC by at-trangle

## Description
test update category
## Reference Requirements

## Reference Isuees

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

2018-06-04 07:08 UTC, at-phuongvu commented on tests/Browser/Admin/UpdateCategoryTest.php
> +        $this->browse(function (Browser $browser) use ($testName, $categoryCurrent ,$categoryOther) {
chỉnh lại cho đúng chút ....

2018-06-04 07:08 UTC, at-phuongvu commented on tests/Browser/Admin/UpdateCategoryTest.php
> +            $browser->visit('admin/categories/' . $categoryCurrent->id . '/edit')
chỉ dùng `id` thì ở trên select ra `id` luôn cũng được

2018-06-04 07:14 UTC, at-phuongvu commented on tests/Browser/Admin/UpdateCategoryTest.php
> +            $browser->visit('admin/categories/' . $categoryCurrent->id . '/edit')
Mà sao chỗ này nhìn ảo ảo vậy ? find thẳng `id` là 1 rồi xong ở dưới cũng chỉ dùng id thôi ?

2018-06-04 07:40 UTC, at-phuongvu commented on tests/Browser/Admin/UpdateCategoryTest.php
> +        $categoryId = Category::find(1)->id;
bỏ cả query đi luôn rồi ném số 1 xuống dưới

2018-06-04 07:43 UTC, at-phuongvu commented
LGTM

2018-06-04 08:25 UTC, ghost requested changes

2018-06-04 08:38 UTC, at-trangle commented on tests/Browser/Admin/UpdateCategoryTest.php
> +}
Cái này e đã xử lý r a...e chỉ cho chọn Parent là cùng cấp vs nó hay cha nó trở lên thôi ạ
` public function edit(Category $category)
    {
        $categories = Category::where('level', '<=', $category->level)->get();
        $data['category'] = $category;
        $data['categories'] = $categories;
        return view('admin.pages.categories.edit', $data);
    }`

2018-06-04 08:42 UTC, at-vietpham commented on tests/Browser/Admin/UpdateCategoryTest.php
> +}
@at-trangle Vậy trường hợp anh edit html thay đổi giá trị trong select box thì sao?

2018-06-05 06:53 UTC, ghost requested changes

2018-06-05 06:53 UTC, at-vietpham commented on tests/Browser/Admin/UpdateCategoryTest.php
> +                    ->click('#edit1');
Chỉ lùi 1 tab so với dòng trên. tương tự những nơi khác.

2018-06-05 08:29 UTC, at-vietpham commented
LGTM 🌵

2018-06-05 08:30 UTC, merged