[Admin] Fix index layout product
AT-PHPIntership/product-tiki pull request #91
Opened 2018-06-04 08:35 UTC by at-khadinh

## Description
Add change index layout product.
## Reference Requirements

## Reference Isuees

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-06-05 10:22 UTC, at-mailuong commented
LGTM

2018-06-06 03:10 UTC, ghost requested changes

2018-06-06 03:10 UTC, at-huenguyen commented on resources/views/admin/pages/products/index.blade.php
> +                        <button class="btn btn-primary btn-danger" onclick="deleteProduct(event, {{ $product->id }}, '{{ $product->name }}')" type="submit"><i class="fa fa-trash"></i></button>
xử lí `onclick...` em nên để trong file js lun nha

2018-06-07 08:42 UTC, at-khadinh commented on resources/views/admin/pages/products/index.blade.php
> +                        <button class="btn btn-primary btn-danger" onclick="deleteProduct(event, {{ $product->id }}, '{{ $product->name }}')" type="submit"><i class="fa fa-trash"></i></button>
trước h tụi e dùng onclick hết chị.

2018-06-08 02:07 UTC, ghost approved these changes

2018-06-08 02:07 UTC, merged