Delete user
AT-PHPIntership/product-tiki pull request #97
Opened 2018-06-05 04:38 UTC by at-mailuong

## Description
admin delete user
## Reference Requirements

## Reference Isuees

## Migrations
NO

## Impacted Areas in Application

## SQL query and `explain`
> explain update `users` set `deleted_at` = "2018-06-03 02:38:34", `updated_at` = "2018-06-03 02:38:34" where `id` = 17\G

```
*************************** 1. row ***************************
           id: 1
  select_type: UPDATE
        table: users
   partitions: NULL
         type: range
possible_keys: PRIMARY
          key: PRIMARY
      key_len: 4
          ref: const
         rows: 1
     filtered: 100.00
        Extra: Using where
1 row in set (0.00 sec)

```

2018-06-05 04:56 UTC, at-trangle commented on public/js/user.js
> +    msg = "Do you want to delete ?";
message ni dùng Lang

2018-06-05 04:56 UTC, at-trangle commented on resources/views/admin/layout/master.blade.php
> +    <script src="/js/user.js"></script>
cái ni dùng yeild

2018-06-05 06:48 UTC, at-trangle commented
LGTM

2018-06-05 06:55 UTC, ghost requested changes

2018-06-05 06:55 UTC, at-vietpham commented on app/Http/Controllers/Admin/UserController.php
> +                $user->delete();
Các comment, review của user này cũng phải được xóa đi

2018-06-05 07:51 UTC, at-trangle commented
LGTM

2018-06-05 08:07 UTC, ghost requested changes

2018-06-05 08:07 UTC, at-vietpham commented on resources/views/admin/pages/users/index.blade.php
> +@section('js')
Tại sao lại phải đưa 2 file nào nào section?

2018-06-05 08:07 UTC, at-vietpham commented on resources/views/admin/pages/users/index.blade.php
> +  <script src="/js/user.js"></script>
File `user.js` chỉ làm mỗi việc delete thì không cần phải có 1 file riêng.

2018-06-05 08:12 UTC, at-mailuong commented on resources/views/admin/pages/users/index.blade.php
> +@section('js')
vì bên master  tụi em dùng @yield('js') trong file master nên bên này em dùng section ạ

2018-06-05 08:15 UTC, at-mailuong commented on resources/views/admin/pages/users/index.blade.php
> +  <script src="/js/user.js"></script>
rứa em bỏ thẳng vào file index luôn hả anh

2018-06-06 02:58 UTC, at-vietpham commented on resources/lang/en/user.php
> +        'messages_delete_js' => 'Do you want to delete ?',
Message này không của riêng user nữa. Có thể đặt trong `messages.php` để key là `delete_record` cũng đc

2018-06-06 04:01 UTC, at-vietpham commented
LGTM 📦

2018-06-06 04:02 UTC, merged